version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    depends_on:
      - fluent-bit
    networks:
      - efk
    logging:
      driver: "fluentd"
      options:
        tag: cloudflared

  fluent-bit:
    image: fluent/fluent-bit:1.5
    volumes:
      - ./fluent-bit/conf:/fluent-bit/etc
    links:
      - "elasticsearch"
    depends_on:
      - elasticsearch
    ports:
      - 24224:24224
      - 5140:5140/udp
      - 2020:2020
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"
    networks:
      - efk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es01
    networks:
      - efk
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=false
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kib01
    links:
      - "elasticsearch"
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - efk

networks:
  efk:
    driver: bridge
